// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwfbpsomfyubzbyvstow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZmJwc29tZnl1YnpieXZzdG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM1MjEsImV4cCI6MjA2NTUxOTUyMX0.cxaeQGg0rXdneGyIl5oXQxs1ODjj8Lt_4o1gY3b6z-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);