# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  #pull_request:
  #  branches: [ "main" ]
jobs:
  build:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Build App
      run: |
        npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.VITE_SUPABASE_SERVICE_ROLE_KEY }}        

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Altere para sua região
    
    - name: Deploy to S3
      run: aws s3 sync dist/ s3://dnw-taskflow --delete
      
    - name: Invalidar o Cache 
      run: aws cloudfront create-invalidation --distribution-id E37SVYBKKI3F0P --path "/*"
